#!/usr/bin/env bash
# clean old artifacts
# compile each .c file to its own .o
# inspect symbols and relocations
# link the object files
# inspect the final ELF
# run the program

set -euo pipefail

main () {
   cc -E "$1" > build/main.i
cc -S "$1" -o build/main.s
cc -c "$1" -o build/main.o
   
}

main "$@"
